name: ci workflow
on:
  pull_request:
    branches:
      - "master"
jobs:
  ci-workflow:
    name: ci workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    
    - name: build 
      run: |
        npm ci
        npm run build --if-present
    - name: test 
      run: npm test
